networks:
  iotech:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1

volumes:
  influxdb-data:
  grafana-storage:
services:
  mqtt:
    image: eclipse-mosquitto:latest
    volumes:
      - ./deployment/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      - iotech
      
  s7-sim:
    image: iotechsys/s7-sim:2.0
    container_name: s7-sim
    networks:
      iotech:
        ipv4_address: 10.10.0.50
    depends_on:
      mqtt:
        condition: service_started
  
  opc-ua-browser:
    container_name: opc-ua-browser
    image: iotechsys/opc-ua-browser:1.0.5
    restart: unless-stopped 
    networks:
      - iotech
    ports: 
      - 8080:8080


  xrt:
    image: iotechsys/xrt-server:2.2
    container_name: xrt-opc-ua
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_started
      s7-sim:
        condition: service_started
      influxdb:
        condition: service_started
    environment:
      LD_LIBRARY_PATH: /opt/iotech/xrt/2.2/lib:/opt/iotech/iot/1.5/lib
      XRT_PROFILE_DIR: /opt/iotech/xrt/2.2/deployment/profiles
      XRT_STATE_DIR: /opt/iotech/xrt/2.2/deployment/state
      XRT_CONFIG_DIR: /opt/iotech/xrt/2.2/deployment/config
      XRT_LICENSE_FILE: /opt/iotech/xrt/2.2/license.json
      XRT_MQTT_BROKER: tcp://mqtt:1883
      S7_SIM_ADDRESS: 10.10.0.50
      XRT_MQTT_USERNAME:
      XRT_MQTT_PASSWORD:
      XRT_INFLUXDB_SERVICE: http://influxdb:8086
      XRT_INFLUXDB_USERNAME: admin
      XRT_INFLUXDB_PASSWORD: adminadminadmin
      XRT_INFLUXDB_BUCKET: test_bucket
      XRT_INFLUXDB_ORG: InfluxOrg
      XRT_INFLUXDB_TOKEN: abcede==
    ports:
      - 5060:80
      - 4840:4840
    volumes:
      - ./deployment/deployment:/opt/iotech/xrt/2.2/deployment
      - ${XRT_LICENSE_FILE}:/opt/iotech/xrt/2.2/license.json

    networks:
      - iotech
  
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadminadmin
      - DOCKER_INFLUXDB_INIT_ORG=InfluxOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=test_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=abcede==
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - iotech

  app:
    build:
      context: ./deployment
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    depends_on:
      mqtt:
        condition: service_started
    networks:
      - iotech

      
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./deployment/grafana/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - iotech

