{
 "title": "CNC Dash",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CNC Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test_bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.device == \"Virtual-Device\")\n|> filter(fn: (r) => r.schedule == \"schedule1\")\n|> filter(fn: (r) => r._field == \"CNCMillTemperature\")"
    }
   ]
  },
  {
   "title": "CNC Vibration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"test_bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.device == \"Virtual-Device\")\n|> filter(fn: (r) => r.schedule == \"schedule1\")\n|> filter(fn: (r) => r._field == \"CNCMillVibration\")"
    }
   ]
  },
  {
   "title": "CNC RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"test_bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.device == \"Virtual-Device\")\n|> filter(fn: (r) => r.schedule == \"schedule1\")\n|> filter(fn: (r) => r._field == \"CNCMillRPM\")"
    }
   ]
  },
  {
   "title": "Alarm Triggered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"test_bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r.device == \"S7-Server\")\n|> filter(fn: (r) => r._field == \"Alarm\")"
    }
   ]
  }
 ]
}