networks:
  iotech:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1

services:
  mqtt:
    image: eclipse-mosquitto:latest
    volumes:
      - ./virtual/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      - iotech

  xrt-virtual:
    image: iotechsys/xrt-server:2.2
    container_name: xrt-device-virtual
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_started
    environment:
      LD_LIBRARY_PATH: /opt/iotech/xrt/2.2/lib:/opt/iotech/iot/1.5/lib
      # Tells XRT where the config for the deployment is
      XRT_PROFILE_DIR: /opt/iotech/xrt/2.2/deployment/profiles
      XRT_STATE_DIR: /opt/iotech/xrt/2.2/deployment/state
      XRT_CONFIG_DIR: /opt/iotech/xrt/2.2/deployment/config
      XRT_LICENSE_FILE: /opt/iotech/xrt/2.2/license.json
      # MQTT Config for XRT. These env vars are used in the MQTT bridge config
      XRT_MQTT_BROKER: tcp://mqtt:1883
      XRT_MQTT_USERNAME:
      XRT_MQTT_PASSWORD:
    ports:
      - 5060:80
    volumes:
      - ./virtual/deployment:/opt/iotech/xrt/2.2/deployment
      - ${XRT_LICENSE_FILE}:/opt/iotech/xrt/2.2/license.json
    networks:
      - iotech
